import sharp from 'sharp'
import type { NormalizedRect, SignerRole } from '@asps-dms/shared'
import { env } from '../config/env.js'
import { logger } from '../utils/logger.js'
import { loadPdfjs, openPdf, renderPage, type PdfPage } from './pdfRaster.service.js'

/**
 * Is there already something in this box?
 *
 * Asked before anything is stamped, so a signature is never painted over a
 * signature. The answer comes from two different kinds of evidence, and which
 * one is used depends on what kind of page it is:
 *
 *   A DIGITAL PAGE - generated by MMC, text and lines drawn as text and lines -
 *   carries a signature or a photograph as an IMAGE, placed where the box is.
 *   So: an image covers the box -> occupied; no image -> empty. Nothing else
 *   is looked at. Printed text and table lines in the box are the form, not a
 *   signature, and must never make it occupied.
 *
 *   A SCANNED PAGE - one image covering most of the page - has whatever was
 *   on the paper baked into that one image, so the image tells nothing. First
 *   the smaller images on top of it are checked, because a signature the DMS
 *   stamped earlier onto a scan is exactly that; if none covers the box, the
 *   box is rendered and its INK is measured: how much of it is darker than
 *   the page's own background. A JPEG or PNG upload is a scanned page by
 *   definition.
 *
 * Every measurement is returned with the verdict and logged, so a threshold
 * can be tuned from real documents rather than guessed at.
 */

export type PageKind = 'digital' | 'scanned'

export type Verdict = 'empty' | 'occupied' | 'uncertain'

export interface BoxToAssess {
  /** Anything the caller wants back on the answer - a template box id, a role. */
  label?: string
  signerRole?: SignerRole
  pageNumber: number
  rect: NormalizedRect
}

/** Where a painted image landed, as fractions of the DISPLAYED page, top-left origin. */
export interface PageImage {
  kind: string
  rect: NormalizedRect
  /** Fraction of the whole page it covers. */
  pageFraction: number
}

export interface OverlapEvidence {
  /** Images that touch the box, largest coverage first. */
  images: number
  /** The largest fraction of the BOX any one image covers. */
  coverage: number
}

export interface InkEvidence {
  /** Percentage of the box's pixels darker than the cut-off. */
  percent: number
  /** What 'white' is on this page: the 90th-percentile brightness inside the box. */
  background: number
  /** background minus the margin, floored - the brightness below which a pixel is ink. */
  cutoff: number
  /**
   * The same box at fixed cut-offs, for comparison only. Never decides
   * anything; present when `compareCutoffs` was asked for (the stamp-check
   * report), so the background-relative rule can be judged against the
   * simpler one it replaced on real documents.
   */
  atCutoff?: { cutoff: number; percent: number }[]
}

export interface BoxAssessment extends BoxToAssess {
  verdict: Verdict
  /** 'image' when an image decided it, 'ink' when the measurement did, 'none' for empty by absence. */
  decidedBy: 'image' | 'ink' | 'none'
  pageKind: PageKind
  overlap: OverlapEvidence
  /** Present only when the ink check ran. */
  ink?: InkEvidence
  reason: string
}

export interface OccupancySettings {
  /** An image covering at least this fraction of the page is a scan background. */
  fullPageMin: number
  /** An image covering at least this fraction of the BOX means occupied. */
  overlapMin: number
  /** Ink at or below this fraction is empty. */
  inkEmptyMax: number
  /** Ink at or above this fraction is occupied; between the two is uncertain. */
  inkOccupiedMin: number
  /** How much darker than the background a pixel must be to count as ink (0-255). */
  inkMargin: number
  /** The cut-off never rises above this, so a very dark scan is not all ink. */
  inkCutoffCeiling: number
  /** Fixed cut-offs to measure alongside, for a report. Not used for any verdict. */
  compareCutoffs?: readonly number[] | undefined
}

export function settingsFromEnv(): OccupancySettings {
  return {
    fullPageMin: env.STAMP_FULL_PAGE_MIN,
    overlapMin: env.STAMP_OVERLAP_MIN,
    inkEmptyMax: env.STAMP_INK_EMPTY_MAX,
    inkOccupiedMin: env.STAMP_INK_OCCUPIED_MIN,
    inkMargin: env.STAMP_INK_MARGIN,
    inkCutoffCeiling: 200,
  }
}

/* -------------------------------------------------------------------------- */
/* Images on a page                                                            */
/* -------------------------------------------------------------------------- */

type Matrix = [number, number, number, number, number, number]

/** m then n, in pdf.js's [a b c d e f] convention. */
function multiply(m: Matrix, n: Matrix): Matrix {
  return [
    m[0] * n[0] + m[1] * n[2],
    m[0] * n[1] + m[1] * n[3],
    m[2] * n[0] + m[3] * n[2],
    m[2] * n[1] + m[3] * n[3],
    m[4] * n[0] + m[5] * n[2] + n[4],
    m[4] * n[1] + m[5] * n[3] + n[5],
  ]
}

function applyTo(m: Matrix, x: number, y: number): [number, number] {
  return [m[0] * x + m[2] * y + m[4], m[1] * x + m[3] * y + m[5]]
}

/**
 * Every image painted on a page, and where.
 *
 * Walks the page's operator list keeping the current transformation matrix -
 * `save` pushes it, `restore` pops it, `transform` multiplies it - and when a
 * paint-image operator comes up, maps the unit square it paints through the
 * matrix into page space, then into the displayed page. The result is in the
 * same units as a placement box, so the two can be compared directly.
 */
export async function imagesOnPage(page: PdfPage): Promise<PageImage[]> {
  const { OPS } = await loadPdfjs()
  const viewport = page.getViewport({ scale: 1 })
  const pageArea = viewport.width * viewport.height

  const paints = new Map<number, string>([
    [OPS.paintImageXObject, 'image'],
    [OPS.paintInlineImageXObject, 'inline image'],
    [OPS.paintImageMaskXObject, 'image mask'],
  ])

  const operators = await page.getOperatorList()
  const stack: Matrix[] = []
  let ctm: Matrix = [1, 0, 0, 1, 0, 0]
  const images: PageImage[] = []

  for (let i = 0; i < operators.fnArray.length; i += 1) {
    const fn = operators.fnArray[i]
    if (fn === OPS.save) {
      stack.push(ctm)
    } else if (fn === OPS.restore) {
      ctm = stack.pop() ?? ctm
    } else if (fn === OPS.transform) {
      ctm = multiply(operators.argsArray[i] as Matrix, ctm)
    } else if (fn !== undefined && paints.has(fn)) {
      const corners = (
        [
          [0, 0],
          [1, 0],
          [0, 1],
          [1, 1],
        ] as const
      ).map(([x, y]) => {
        const [px, py] = applyTo(ctm, x, y)
        return viewport.convertToViewportPoint(px, py) as [number, number]
      })
      const xs = corners.map((c) => c[0])
      const ys = corners.map((c) => c[1])
      const x0 = Math.max(0, Math.min(...xs))
      const x1 = Math.min(viewport.width, Math.max(...xs))
      const y0 = Math.max(0, Math.min(...ys))
      const y1 = Math.min(viewport.height, Math.max(...ys))
      if (x1 <= x0 || y1 <= y0) continue
      images.push({
        kind: paints.get(fn) ?? 'image',
        rect: {
          x: x0 / viewport.width,
          y: y0 / viewport.height,
          width: (x1 - x0) / viewport.width,
          height: (y1 - y0) / viewport.height,
        },
        pageFraction: ((x1 - x0) * (y1 - y0)) / pageArea,
      })
    }
  }

  return images
}

/** What fraction of the BOX an image covers. Images outside it count for nothing. */
export function boxCoverage(box: NormalizedRect, image: NormalizedRect): number {
  const x0 = Math.max(box.x, image.x)
  const y0 = Math.max(box.y, image.y)
  const x1 = Math.min(box.x + box.width, image.x + image.width)
  const y1 = Math.min(box.y + box.height, image.y + image.height)
  if (x1 <= x0 || y1 <= y0) return 0
  return ((x1 - x0) * (y1 - y0)) / (box.width * box.height)
}

/* -------------------------------------------------------------------------- */
/* Ink                                                                         */
/* -------------------------------------------------------------------------- */

export interface GreyPixels {
  data: Buffer
  width: number
  height: number
}

/** A rendered page (or an uploaded image), greyscale, one byte per pixel. */
export async function toGrey(png: Buffer, orient: boolean = false): Promise<GreyPixels> {
  let pipeline = sharp(png, { failOn: 'error' })
  if (orient) pipeline = pipeline.rotate()
  const { data, info } = await pipeline.greyscale().raw().toBuffer({ resolveWithObject: true })
  return { data, width: info.width, height: info.height }
}

/**
 * How much of the box is ink, judged against the box's own background.
 *
 * A scanner's 'white' is not 255: on one office scanner it is around 190, on
 * another 235. A fixed cut-off calls one scan's blank paper all ink and misses
 * a faint signature on the other. So the box's background is measured first -
 * the 90th-percentile brightness, which on any box that is mostly paper IS
 * the paper - and a pixel is ink when it is `margin` darker than that. A
 * ceiling stops a very dark scan from making everything ink.
 */
export function inkFraction(
  pixels: GreyPixels,
  box: NormalizedRect,
  settings: Pick<OccupancySettings, 'inkMargin' | 'inkCutoffCeiling' | 'compareCutoffs'>,
): InkEvidence {
  const x0 = Math.max(0, Math.floor(box.x * pixels.width))
  const y0 = Math.max(0, Math.floor(box.y * pixels.height))
  const x1 = Math.min(pixels.width, Math.ceil((box.x + box.width) * pixels.width))
  const y1 = Math.min(pixels.height, Math.ceil((box.y + box.height) * pixels.height))

  const histogram = new Uint32Array(256)
  let total = 0
  for (let y = y0; y < y1; y += 1) {
    const row = y * pixels.width
    for (let x = x0; x < x1; x += 1) {
      const value = pixels.data[row + x] ?? 255
      histogram[value] = (histogram[value] ?? 0) + 1
      total += 1
    }
  }
  if (total === 0) return { percent: 0, background: 255, cutoff: 0 }

  // The 90th percentile, walking down from white.
  let background = 255
  let seen = 0
  for (let v = 255; v >= 0; v -= 1) {
    seen += histogram[v] ?? 0
    if (seen >= total * 0.1) {
      background = v
      break
    }
  }

  const cutoff = Math.min(settings.inkCutoffCeiling, background - settings.inkMargin)
  const below = (limit: number): number => {
    let ink = 0
    for (let v = 0; v < limit; v += 1) ink += histogram[v] ?? 0
    return (100 * ink) / total
  }

  const evidence: InkEvidence = { percent: below(cutoff), background, cutoff }
  if (settings.compareCutoffs && settings.compareCutoffs.length > 0) {
    evidence.atCutoff = settings.compareCutoffs.map((fixed) => ({
      cutoff: fixed,
      percent: below(fixed),
    }))
  }
  return evidence
}

/* -------------------------------------------------------------------------- */
/* The verdict                                                                 */
/* -------------------------------------------------------------------------- */

function verdictFromInk(ink: InkEvidence, settings: OccupancySettings): Verdict {
  const fraction = ink.percent / 100
  if (fraction <= settings.inkEmptyMax) return 'empty'
  if (fraction >= settings.inkOccupiedMin) return 'occupied'
  return 'uncertain'
}

interface PageEvidence {
  kind: PageKind
  /** Images that are NOT the scan background. */
  images: PageImage[]
  /** Lazily rendered, once per page, only when an ink check needs it. */
  grey: () => Promise<GreyPixels>
}

function assessAgainst(box: BoxToAssess, evidence: PageEvidence, settings: OccupancySettings) {
  return async (): Promise<BoxAssessment> => {
    const covering = evidence.images
      .map((image) => boxCoverage(box.rect, image.rect))
      .filter((coverage) => coverage > 0)
      .sort((a, b) => b - a)
    const overlap: OverlapEvidence = { images: covering.length, coverage: covering[0] ?? 0 }

    // An image on the box decides it, on either kind of page: on a digital page
    // that is the signature; on a scan it is a signature the DMS put there.
    if (overlap.coverage >= settings.overlapMin) {
      return {
        ...box,
        verdict: 'occupied',
        decidedBy: 'image',
        pageKind: evidence.kind,
        overlap,
        reason: `an image covers ${Math.round(overlap.coverage * 100)}% of the box`,
      }
    }

    if (evidence.kind === 'digital') {
      // Nothing but the form itself. Text and lines are not a signature.
      return {
        ...box,
        verdict: 'empty',
        decidedBy: 'none',
        pageKind: 'digital',
        overlap,
        reason: 'no image on the box',
      }
    }

    const ink = inkFraction(await evidence.grey(), box.rect, settings)
    const verdict = verdictFromInk(ink, settings)
    return {
      ...box,
      verdict,
      decidedBy: verdict === 'empty' ? 'none' : 'ink',
      pageKind: 'scanned',
      overlap,
      ink,
      reason:
        `${ink.percent.toFixed(2)}% ink against a background of ${ink.background}` +
        ` (cut-off ${ink.cutoff})`,
    }
  }
}

/**
 * Assesses every box against the document it would be stamped on.
 *
 * Reads the file; writes nothing. Pages are rendered at most once each, and
 * only when a box on them needs the ink check. An image upload is one
 * scanned page.
 */
export async function assessBoxes(
  source: Buffer,
  mimeType: string,
  boxes: readonly BoxToAssess[],
  settings: OccupancySettings = settingsFromEnv(),
): Promise<BoxAssessment[]> {
  if (boxes.length === 0) return []

  if (mimeType !== 'application/pdf') {
    // The whole document is one picture: a scanned page with no images on it
    // to speak of, so every box goes to the ink check. Orientation from the
    // EXIF header is applied so the box lands where the picture is seen.
    let grey: Promise<GreyPixels> | null = null
    const evidence: PageEvidence = {
      kind: 'scanned',
      images: [],
      grey: () => (grey ??= toGrey(source, true)),
    }
    const results = await Promise.all(boxes.map((box) => assessAgainst(box, evidence, settings)()))
    for (const result of results) logAssessment(result)
    return results
  }

  const pdf = await openPdf(source)
  try {
    const byPage = new Map<number, PageEvidence>()

    const evidenceFor = async (pageNumber: number): Promise<PageEvidence | null> => {
      const cached = byPage.get(pageNumber)
      if (cached) return cached
      if (pageNumber < 1 || pageNumber > pdf.numPages) return null

      const page = await pdf.getPage(pageNumber)
      const all = await imagesOnPage(page)
      const background = all.filter((image) => image.pageFraction >= settings.fullPageMin)
      const evidence: PageEvidence = {
        kind: background.length > 0 ? 'scanned' : 'digital',
        images: all.filter((image) => image.pageFraction < settings.fullPageMin),
        grey: (() => {
          let grey: Promise<GreyPixels> | null = null
          return () => (grey ??= renderPage(page).then((png) => toGrey(png)))
        })(),
      }
      byPage.set(pageNumber, evidence)
      return evidence
    }

    const results: BoxAssessment[] = []
    for (const box of boxes) {
      const evidence = await evidenceFor(box.pageNumber)
      if (!evidence) {
        results.push({
          ...box,
          verdict: 'uncertain',
          decidedBy: 'none',
          pageKind: 'digital',
          overlap: { images: 0, coverage: 0 },
          reason: `the document has no page ${box.pageNumber}`,
        })
        continue
      }
      const result = await assessAgainst(box, evidence, settings)()
      logAssessment(result)
      results.push(result)
    }
    return results
  } finally {
    await pdf.destroy()
  }
}

function logAssessment(result: BoxAssessment): void {
  logger.info(
    {
      box: result.label ?? null,
      role: result.signerRole ?? null,
      page: result.pageNumber,
      pageKind: result.pageKind,
      verdict: result.verdict,
      decidedBy: result.decidedBy,
      overlapImages: result.overlap.images,
      overlapCoverage: Number(result.overlap.coverage.toFixed(3)),
      inkPercent: result.ink ? Number(result.ink.percent.toFixed(2)) : null,
      inkBackground: result.ink?.background ?? null,
      inkCutoff: result.ink?.cutoff ?? null,
    },
    'Box occupancy assessed',
  )
}
