/* =============================================================================
   ASPS-DMS  -  0001  Initial schema
   Target: Microsoft SQL Server 2014  (compatibility level 120)

   SQL Server 2014 compatibility notes - deliberately avoided throughout:
     - DROP ... IF EXISTS        (2016+)  -> IF OBJECT_ID(...) IS NOT NULL
     - STRING_AGG               (2017+)  -> FOR XML PATH, or aggregate in Node
     - TRIM                     (2017+)  -> LTRIM(RTRIM(x))
     - JSON functions           (2016+)  -> NVARCHAR(MAX), parsed in Node
     - Temporal tables          (2016+)  -> dbo.AuditLogs is our history
     - AT TIME ZONE             (2016+)  -> all instants stored UTC

   Used, and verified available in 2014:
     - SEQUENCE, OFFSET/FETCH, TRY_CONVERT, IIF   (2012+)
     - Filtered indexes, DATE, DATETIME2          (2008+)

   All instants are UTC via SYSUTCDATETIME(). Calendar values (JoiningDate,
   DueDate) are DATE, so no timezone conversion can ever shift them.
   ============================================================================= */

SET NOCOUNT ON;
GO

/* -----------------------------------------------------------------------------
   Roles
   -------------------------------------------------------------------------- */
IF OBJECT_ID(N'dbo.Roles', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.Roles
    (
        RoleId      INT             NOT NULL IDENTITY(1,1),
        RoleName    VARCHAR(30)     NOT NULL,
        Description NVARCHAR(200)   NULL,
        CreatedAt   DATETIME2(3)    NOT NULL CONSTRAINT DF_Roles_CreatedAt DEFAULT (SYSUTCDATETIME()),
        CONSTRAINT PK_Roles PRIMARY KEY CLUSTERED (RoleId),
        CONSTRAINT UQ_Roles_RoleName UNIQUE (RoleName)
    );
END
GO

/* -----------------------------------------------------------------------------
   Users
   Passwords are stored as scrypt hash + per-user salt. Never plain text.
   -------------------------------------------------------------------------- */
IF OBJECT_ID(N'dbo.Users', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.Users
    (
        UserId              INT             NOT NULL IDENTITY(1,1),
        Username            NVARCHAR(100)   NOT NULL,
        PasswordHash        VARBINARY(256)  NOT NULL,
        PasswordSalt        VARBINARY(64)   NOT NULL,
        PasswordAlgorithm   VARCHAR(30)     NOT NULL CONSTRAINT DF_Users_PwdAlgo DEFAULT ('scrypt'),
        FullName            NVARCHAR(150)   NOT NULL,
        RoleId              INT             NOT NULL,
        IsActive            BIT             NOT NULL CONSTRAINT DF_Users_IsActive DEFAULT (1),
        MustChangePassword  BIT             NOT NULL CONSTRAINT DF_Users_MustChangePwd DEFAULT (1),
        LastLoginAt         DATETIME2(3)    NULL,
        FailedLoginCount    INT             NOT NULL CONSTRAINT DF_Users_FailedLogin DEFAULT (0),
        LockedUntil         DATETIME2(3)    NULL,
        CreatedAt           DATETIME2(3)    NOT NULL CONSTRAINT DF_Users_CreatedAt DEFAULT (SYSUTCDATETIME()),
        UpdatedAt           DATETIME2(3)    NOT NULL CONSTRAINT DF_Users_UpdatedAt DEFAULT (SYSUTCDATETIME()),
        CONSTRAINT PK_Users PRIMARY KEY CLUSTERED (UserId),
        CONSTRAINT UQ_Users_Username UNIQUE (Username),
        CONSTRAINT FK_Users_Roles FOREIGN KEY (RoleId) REFERENCES dbo.Roles (RoleId)
    );

    CREATE NONCLUSTERED INDEX IX_Users_RoleId ON dbo.Users (RoleId);
END
GO

/* -----------------------------------------------------------------------------
   Sessions
   Server-side, revocable. Only the SHA-256 of the token is stored, so a leak of
   this table does not yield usable session tokens.
   -------------------------------------------------------------------------- */
IF OBJECT_ID(N'dbo.Sessions', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.Sessions
    (
        SessionId       BIGINT          NOT NULL IDENTITY(1,1),
        UserId          INT             NOT NULL,
        TokenHash       VARBINARY(32)   NOT NULL,
        IssuedAt        DATETIME2(3)    NOT NULL CONSTRAINT DF_Sessions_IssuedAt DEFAULT (SYSUTCDATETIME()),
        LastSeenAt      DATETIME2(3)    NOT NULL CONSTRAINT DF_Sessions_LastSeen DEFAULT (SYSUTCDATETIME()),
        ExpiresAt       DATETIME2(3)    NOT NULL,
        AbsoluteExpiry  DATETIME2(3)    NOT NULL,
        RevokedAt       DATETIME2(3)    NULL,
        IpAddress       VARCHAR(45)     NULL,
        UserAgent       NVARCHAR(300)   NULL,
        CONSTRAINT PK_Sessions PRIMARY KEY CLUSTERED (SessionId),
        CONSTRAINT UQ_Sessions_TokenHash UNIQUE (TokenHash),
        CONSTRAINT FK_Sessions_Users FOREIGN KEY (UserId) REFERENCES dbo.Users (UserId)
    );

    CREATE NONCLUSTERED INDEX IX_Sessions_UserId_ExpiresAt ON dbo.Sessions (UserId, ExpiresAt);
END
GO

/* -----------------------------------------------------------------------------
   Employees
   EmployeeCode is generated by dbo.EmployeeCodeSeq inside the creation
   transaction; the UNIQUE constraint is the final guarantee. Department and
   Designation are NULLable by business rule (Section 89, items 4 and 5).
   -------------------------------------------------------------------------- */
IF OBJECT_ID(N'dbo.Employees', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.Employees
    (
        EmployeeId    INT             NOT NULL IDENTITY(1,1),
        EmployeeCode  VARCHAR(20)     NOT NULL,
        EmployeeName  NVARCHAR(150)   NOT NULL,
        JoiningDate   DATE            NOT NULL,
        Department    NVARCHAR(100)   NULL,
        Designation   NVARCHAR(100)   NULL,
        IsActive      BIT             NOT NULL CONSTRAINT DF_Employees_IsActive DEFAULT (1),
        CreatedBy     INT             NULL,
        CreatedAt     DATETIME2(3)    NOT NULL CONSTRAINT DF_Employees_CreatedAt DEFAULT (SYSUTCDATETIME()),
        UpdatedAt     DATETIME2(3)    NOT NULL CONSTRAINT DF_Employees_UpdatedAt DEFAULT (SYSUTCDATETIME()),
        CONSTRAINT PK_Employees PRIMARY KEY CLUSTERED (EmployeeId),
        CONSTRAINT UQ_Employees_EmployeeCode UNIQUE (EmployeeCode),
        CONSTRAINT CK_Employees_Name_NotBlank CHECK (LEN(LTRIM(RTRIM(EmployeeName))) > 0),
        CONSTRAINT FK_Employees_CreatedBy FOREIGN KEY (CreatedBy) REFERENCES dbo.Users (UserId)
    );

    CREATE NONCLUSTERED INDEX IX_Employees_EmployeeName ON dbo.Employees (EmployeeName);
    CREATE NONCLUSTERED INDEX IX_Employees_Department   ON dbo.Employees (Department);
    CREATE NONCLUSTERED INDEX IX_Employees_IsActive     ON dbo.Employees (IsActive) INCLUDE (EmployeeCode, EmployeeName);
END
GO

/* Employee code sequence. Yields EMP001..EMP999 then EMP1000 onwards, so it
   scales past 999 without collision or renumbering (Section 13). */
IF NOT EXISTS (SELECT 1 FROM sys.sequences WHERE name = N'EmployeeCodeSeq' AND schema_id = SCHEMA_ID(N'dbo'))
BEGIN
    CREATE SEQUENCE dbo.EmployeeCodeSeq
        AS INT
        START WITH 1
        INCREMENT BY 1
        MINVALUE 1
        NO CYCLE
        CACHE 10;
END
GO

/* -----------------------------------------------------------------------------
   DocumentTypes
   The document checklist is configuration, not code. Adding a document type
   later requires no application change (Section 15).
   -------------------------------------------------------------------------- */
IF OBJECT_ID(N'dbo.DocumentTypes', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.DocumentTypes
    (
        DocumentTypeId    INT             NOT NULL IDENTITY(1,1),
        DocumentName      NVARCHAR(150)   NOT NULL,
        DocumentCode      VARCHAR(50)     NOT NULL,
        IsMandatory       BIT             NOT NULL CONSTRAINT DF_DocTypes_IsMandatory DEFAULT (0),
        IsActive          BIT             NOT NULL CONSTRAINT DF_DocTypes_IsActive DEFAULT (1),
        RequiresSignature BIT             NOT NULL CONSTRAINT DF_DocTypes_ReqSig DEFAULT (0),
        DeadlineValue     INT             NULL,
        DeadlineUnit      VARCHAR(10)     NULL,
        SortOrder         INT             NOT NULL CONSTRAINT DF_DocTypes_SortOrder DEFAULT (0),
        CreatedAt         DATETIME2(3)    NOT NULL CONSTRAINT DF_DocTypes_CreatedAt DEFAULT (SYSUTCDATETIME()),
        UpdatedAt         DATETIME2(3)    NOT NULL CONSTRAINT DF_DocTypes_UpdatedAt DEFAULT (SYSUTCDATETIME()),
        CONSTRAINT PK_DocumentTypes PRIMARY KEY CLUSTERED (DocumentTypeId),
        CONSTRAINT UQ_DocumentTypes_Name UNIQUE (DocumentName),
        CONSTRAINT UQ_DocumentTypes_Code UNIQUE (DocumentCode),
        CONSTRAINT CK_DocTypes_DeadlineUnit CHECK (DeadlineUnit IS NULL OR DeadlineUnit IN ('DAY', 'MONTH')),
        CONSTRAINT CK_DocTypes_DeadlineValue CHECK (DeadlineValue IS NULL OR DeadlineValue >= 0),
        /* Value and unit are meaningful only together. */
        CONSTRAINT CK_DocTypes_DeadlinePair CHECK (
            (DeadlineValue IS NULL AND DeadlineUnit IS NULL)
            OR (DeadlineValue IS NOT NULL AND DeadlineUnit IS NOT NULL)
        )
    );

    CREATE NONCLUSTERED INDEX IX_DocumentTypes_Active_Sort ON dbo.DocumentTypes (IsActive, SortOrder);
END
GO

/* -----------------------------------------------------------------------------
   EmployeeDocuments
   One row per (employee, document type). Rows are materialised as 'Pending'
   when the employee is created, which turns "what is pending / overdue" into a
   plain indexed query instead of a cross join at read time.
   -------------------------------------------------------------------------- */
IF OBJECT_ID(N'dbo.EmployeeDocuments', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.EmployeeDocuments
    (
        DocumentId        INT             NOT NULL IDENTITY(1,1),
        EmployeeId        INT             NOT NULL,
        DocumentTypeId    INT             NOT NULL,

        OriginalFileName  NVARCHAR(260)   NULL,
        StoredFileName    VARCHAR(100)    NULL,
        OriginalFilePath  NVARCHAR(500)   NULL,
        ProcessedFilePath NVARCHAR(500)   NULL,
        FileSizeBytes     BIGINT          NULL,
        MimeType          VARCHAR(100)    NULL,
        Sha256            VARBINARY(32)   NULL,
        PageCount         INT             NULL,

        Status            VARCHAR(20)     NOT NULL CONSTRAINT DF_EmpDocs_Status DEFAULT ('Pending'),
        SignatureStatus   VARCHAR(20)     NOT NULL CONSTRAINT DF_EmpDocs_SigStatus DEFAULT ('NotRequired'),

        DueDate           DATE            NULL,
        UploadedBy        INT             NULL,
        UploadedAt        DATETIME2(3)    NULL,
        VerifiedBy        INT             NULL,
        VerifiedAt        DATETIME2(3)    NULL,
        RejectionReason   NVARCHAR(500)   NULL,

        IsActive          BIT             NOT NULL CONSTRAINT DF_EmpDocs_IsActive DEFAULT (1),
        CreatedAt         DATETIME2(3)    NOT NULL CONSTRAINT DF_EmpDocs_CreatedAt DEFAULT (SYSUTCDATETIME()),
        UpdatedAt         DATETIME2(3)    NOT NULL CONSTRAINT DF_EmpDocs_UpdatedAt DEFAULT (SYSUTCDATETIME()),

        CONSTRAINT PK_EmployeeDocuments PRIMARY KEY CLUSTERED (DocumentId),
        CONSTRAINT FK_EmpDocs_Employees FOREIGN KEY (EmployeeId) REFERENCES dbo.Employees (EmployeeId),
        CONSTRAINT FK_EmpDocs_DocumentTypes FOREIGN KEY (DocumentTypeId) REFERENCES dbo.DocumentTypes (DocumentTypeId),
        CONSTRAINT FK_EmpDocs_UploadedBy FOREIGN KEY (UploadedBy) REFERENCES dbo.Users (UserId),
        CONSTRAINT FK_EmpDocs_VerifiedBy FOREIGN KEY (VerifiedBy) REFERENCES dbo.Users (UserId),

        CONSTRAINT CK_EmpDocs_Status CHECK (Status IN ('Pending', 'Uploaded', 'UnderReview', 'Verified', 'Rejected')),
        CONSTRAINT CK_EmpDocs_SigStatus CHECK (SignatureStatus IN ('NotRequired', 'PendingDetection', 'ReviewRequired', 'Added', 'Skipped')),
        /* A rejected document must carry a reason; HR is never left guessing. */
        CONSTRAINT CK_EmpDocs_RejectionReason CHECK (Status <> 'Rejected' OR RejectionReason IS NOT NULL),
        /* Anything past Pending must have a stored file behind it. */
        CONSTRAINT CK_EmpDocs_FileRequired CHECK (Status = 'Pending' OR StoredFileName IS NOT NULL)
    );

    /* One active row per employee/document type. Filtered so that archived rows
       from a previous replacement do not collide. */
    CREATE UNIQUE NONCLUSTERED INDEX UX_EmpDocs_Employee_Type
        ON dbo.EmployeeDocuments (EmployeeId, DocumentTypeId)
        WHERE IsActive = 1;

    CREATE NONCLUSTERED INDEX IX_EmpDocs_EmployeeId ON dbo.EmployeeDocuments (EmployeeId) INCLUDE (Status, SignatureStatus, DueDate);
    CREATE NONCLUSTERED INDEX IX_EmpDocs_Status     ON dbo.EmployeeDocuments (Status)     INCLUDE (EmployeeId, DocumentTypeId, DueDate);
    CREATE NONCLUSTERED INDEX IX_EmpDocs_DueDate    ON dbo.EmployeeDocuments (DueDate)    INCLUDE (EmployeeId, DocumentTypeId, Status);
    CREATE NONCLUSTERED INDEX IX_EmpDocs_SigStatus  ON dbo.EmployeeDocuments (SignatureStatus) INCLUDE (EmployeeId, DocumentTypeId);
END
GO

/* -----------------------------------------------------------------------------
   EmployeeSignatures
   Uploaded once per employee and reused for every document (Section 24).
   Replacing sets the previous row IsActive = 0 rather than deleting it, so the
   history of which signature image was applied when is preserved.
   -------------------------------------------------------------------------- */
IF OBJECT_ID(N'dbo.EmployeeSignatures', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.EmployeeSignatures
    (
        EmployeeSignatureId INT             NOT NULL IDENTITY(1,1),
        EmployeeId          INT             NOT NULL,
        StoredFileName      VARCHAR(100)    NOT NULL,
        FilePath            NVARCHAR(500)   NOT NULL,
        OriginalFileName    NVARCHAR(260)   NULL,
        MimeType            VARCHAR(100)    NOT NULL,
        FileSizeBytes       BIGINT          NULL,
        WidthPx             INT             NULL,
        HeightPx            INT             NULL,
        IsActive            BIT             NOT NULL CONSTRAINT DF_EmpSig_IsActive DEFAULT (1),
        UploadedBy          INT             NULL,
        UploadedAt          DATETIME2(3)    NOT NULL CONSTRAINT DF_EmpSig_UploadedAt DEFAULT (SYSUTCDATETIME()),
        UpdatedAt           DATETIME2(3)    NOT NULL CONSTRAINT DF_EmpSig_UpdatedAt DEFAULT (SYSUTCDATETIME()),
        CONSTRAINT PK_EmployeeSignatures PRIMARY KEY CLUSTERED (EmployeeSignatureId),
        CONSTRAINT FK_EmpSig_Employees FOREIGN KEY (EmployeeId) REFERENCES dbo.Employees (EmployeeId),
        CONSTRAINT FK_EmpSig_UploadedBy FOREIGN KEY (UploadedBy) REFERENCES dbo.Users (UserId)
    );

    /* At most one active signature per employee. */
    CREATE UNIQUE NONCLUSTERED INDEX UX_EmpSig_Employee_Active
        ON dbo.EmployeeSignatures (EmployeeId)
        WHERE IsActive = 1;
END
GO

/* -----------------------------------------------------------------------------
   SignaturePlacements
   X / Y / Width / Height are NORMALIZED 0..1 in displayed page space with a
   top-left origin. PageRotation records the page's /Rotate so the backend can
   map back into unrotated PDF user space. No pixel, DPI or zoom value is ever
   stored. See docs/coordinate-system.md.
   -------------------------------------------------------------------------- */
IF OBJECT_ID(N'dbo.SignaturePlacements', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.SignaturePlacements
    (
        SignaturePlacementId INT           NOT NULL IDENTITY(1,1),
        DocumentId           INT           NOT NULL,
        EmployeeId           INT           NOT NULL,
        PageNumber           INT           NOT NULL,
        X                    FLOAT         NOT NULL,
        Y                    FLOAT         NOT NULL,
        Width                FLOAT         NOT NULL,
        Height               FLOAT         NOT NULL,
        PageRotation         INT           NOT NULL CONSTRAINT DF_SigPlace_Rotation DEFAULT (0),
        Method               VARCHAR(20)   NOT NULL,
        DetectionMethod      VARCHAR(20)   NOT NULL,
        Confidence           FLOAT         NULL,
        IsApplied            BIT           NOT NULL CONSTRAINT DF_SigPlace_IsApplied DEFAULT (0),
        CreatedBy            INT           NULL,
        CreatedAt            DATETIME2(3)  NOT NULL CONSTRAINT DF_SigPlace_CreatedAt DEFAULT (SYSUTCDATETIME()),
        UpdatedAt            DATETIME2(3)  NOT NULL CONSTRAINT DF_SigPlace_UpdatedAt DEFAULT (SYSUTCDATETIME()),

        CONSTRAINT PK_SignaturePlacements PRIMARY KEY CLUSTERED (SignaturePlacementId),
        CONSTRAINT FK_SigPlace_Documents FOREIGN KEY (DocumentId) REFERENCES dbo.EmployeeDocuments (DocumentId),
        CONSTRAINT FK_SigPlace_Employees FOREIGN KEY (EmployeeId) REFERENCES dbo.Employees (EmployeeId),
        CONSTRAINT FK_SigPlace_CreatedBy FOREIGN KEY (CreatedBy) REFERENCES dbo.Users (UserId),

        CONSTRAINT CK_SigPlace_Method CHECK (Method IN ('Automatic', 'Manual', 'Adjusted')),
        CONSTRAINT CK_SigPlace_DetectionMethod CHECK (DetectionMethod IN ('OCR', 'CV', 'Combined', 'Manual')),
        CONSTRAINT CK_SigPlace_PageNumber CHECK (PageNumber >= 1),
        CONSTRAINT CK_SigPlace_Rotation CHECK (PageRotation IN (0, 90, 180, 270)),
        CONSTRAINT CK_SigPlace_Confidence CHECK (Confidence IS NULL OR (Confidence >= 0 AND Confidence <= 1)),
        /* Bounds are enforced in the database as well as in the service layer:
           a placement can never be stored partly off the page. */
        CONSTRAINT CK_SigPlace_Bounds CHECK (
            X >= 0 AND Y >= 0
            AND Width  > 0 AND Height > 0
            AND X + Width  <= 1.0001
            AND Y + Height <= 1.0001
        )
    );

    CREATE NONCLUSTERED INDEX IX_SigPlace_Document_Page ON dbo.SignaturePlacements (DocumentId, PageNumber);
END
GO

/* -----------------------------------------------------------------------------
   AuditLogs
   Metadata is sanitised NVARCHAR(MAX) JSON (parsed in Node - SQL 2014 has no
   native JSON type). Passwords, tokens and document contents are stripped
   before insert; see shared/src/constants/audit.ts AUDIT_REDACTED_KEYS.
   -------------------------------------------------------------------------- */
IF OBJECT_ID(N'dbo.AuditLogs', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.AuditLogs
    (
        AuditLogId  BIGINT          NOT NULL IDENTITY(1,1),
        UserId      INT             NULL,
        Action      VARCHAR(50)     NOT NULL,
        EntityType  VARCHAR(50)     NOT NULL,
        EntityId    VARCHAR(50)     NULL,
        IpAddress   VARCHAR(45)     NULL,
        Metadata    NVARCHAR(MAX)   NULL,
        Timestamp   DATETIME2(3)    NOT NULL CONSTRAINT DF_AuditLogs_Timestamp DEFAULT (SYSUTCDATETIME()),
        CONSTRAINT PK_AuditLogs PRIMARY KEY CLUSTERED (AuditLogId),
        CONSTRAINT FK_AuditLogs_Users FOREIGN KEY (UserId) REFERENCES dbo.Users (UserId)
    );

    CREATE NONCLUSTERED INDEX IX_AuditLogs_Timestamp ON dbo.AuditLogs (Timestamp DESC);
    CREATE NONCLUSTERED INDEX IX_AuditLogs_Entity    ON dbo.AuditLogs (EntityType, EntityId);
    CREATE NONCLUSTERED INDEX IX_AuditLogs_UserId    ON dbo.AuditLogs (UserId, Timestamp DESC);
END
GO

/* -----------------------------------------------------------------------------
   AppSettings
   Small key/value store so operational thresholds (for example the "Due Soon"
   window) are configurable from Settings rather than hard-coded.
   -------------------------------------------------------------------------- */
IF OBJECT_ID(N'dbo.AppSettings', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.AppSettings
    (
        SettingKey   VARCHAR(100)   NOT NULL,
        SettingValue NVARCHAR(500)  NOT NULL,
        Description  NVARCHAR(300)  NULL,
        UpdatedBy    INT            NULL,
        UpdatedAt    DATETIME2(3)   NOT NULL CONSTRAINT DF_AppSettings_UpdatedAt DEFAULT (SYSUTCDATETIME()),
        CONSTRAINT PK_AppSettings PRIMARY KEY CLUSTERED (SettingKey),
        CONSTRAINT FK_AppSettings_Users FOREIGN KEY (UpdatedBy) REFERENCES dbo.Users (UserId)
    );
END
GO
