/* =============================================================================
   ASPS-DMS  -  0035  Where the signatures and the photograph go, per document type
   Target: Microsoft SQL Server 2014  (compatibility level 120)

   HR was dragging a box onto every single document before it could be
   stamped: 566 employees times seven forms is not a thing anyone can do. The
   forms are generated by one piece of software from one layout each, so the
   boxes are the same on every employee's copy. This records them ONCE, per
   document type, as a template.

   A SEPARATE TABLE FROM SignaturePlacements, deliberately. That table is the
   record of what was actually stamped on each document and stays exactly as
   it is; this is where a stamp WOULD go on a document of this type. Saving a
   template reads and writes nothing else - not a document, not a stored
   file - and there is no action that applies a template to the documents
   already there. It is groundwork: the next change stamps NEW uploads from it.

   THE SAMPLE IS THE TEMPLATE'S CONTRACT. A template is drawn on one real
   document of the type, and the coordinates are fractions of that page. So
   the sample's page size, rotation and page count are recorded with every
   box, and a document that does not match them - a form redesigned since,
   a scan instead of the generated PDF - is refused rather than stamped in
   the wrong place.

   The same CHECK constraints as SignaturePlacements, less the ones about a
   stamp that has happened: no Method, no DetectionMethod, no Confidence, no
   IsApplied, no SignerUserId. A template is always drawn by hand, and it
   names no signer because nobody has signed anything yet.

   SampleDocumentId carries no foreign key on purpose: it is a caption -
   'set from EMP001's form' - and archiving that document later must not be
   stopped by a template that happened to be drawn on it.
   ============================================================================= */

SET NOCOUNT ON;
GO

IF OBJECT_ID(N'dbo.DocumentTypePlacements', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.DocumentTypePlacements
    (
        DocumentTypePlacementId INT           NOT NULL IDENTITY(1,1),
        DocumentTypeId          INT           NOT NULL,
        SignerRole              VARCHAR(20)   NOT NULL,
        PageNumber              INT           NOT NULL,
        X                       FLOAT         NOT NULL,
        Y                       FLOAT         NOT NULL,
        Width                   FLOAT         NOT NULL,
        Height                  FLOAT         NOT NULL,
        PageRotation            INT           NOT NULL CONSTRAINT DF_TypePlace_Rotation DEFAULT (0),
        /* The sample page this box was drawn on: unrotated MediaBox, in points. */
        PageWidthPt             FLOAT         NOT NULL,
        PageHeightPt            FLOAT         NOT NULL,
        SamplePageCount         INT           NOT NULL,
        SampleDocumentId        INT           NULL,
        CreatedBy               INT           NOT NULL,
        CreatedAt               DATETIME2(3)  NOT NULL CONSTRAINT DF_TypePlace_CreatedAt DEFAULT (SYSUTCDATETIME()),

        CONSTRAINT PK_DocumentTypePlacements PRIMARY KEY CLUSTERED (DocumentTypePlacementId),
        CONSTRAINT FK_TypePlace_DocumentTypes FOREIGN KEY (DocumentTypeId) REFERENCES dbo.DocumentTypes (DocumentTypeId),
        CONSTRAINT FK_TypePlace_CreatedBy FOREIGN KEY (CreatedBy) REFERENCES dbo.Users (UserId),

        CONSTRAINT CK_TypePlace_SignerRole CHECK (SignerRole IN ('Employee', 'Authoriser', 'Photo')),
        CONSTRAINT CK_TypePlace_PageNumber CHECK (PageNumber >= 1),
        CONSTRAINT CK_TypePlace_Rotation CHECK (PageRotation IN (0, 90, 180, 270)),
        CONSTRAINT CK_TypePlace_PageSize CHECK (PageWidthPt > 0 AND PageHeightPt > 0),
        CONSTRAINT CK_TypePlace_PageCount CHECK (SamplePageCount >= 1 AND PageNumber <= SamplePageCount),
        /* Bounds in the database as well as the service: a box can never be
           stored partly off the page. Identical to CK_SigPlace_Bounds. */
        CONSTRAINT CK_TypePlace_Bounds CHECK (
            X >= 0 AND Y >= 0
            AND Width  > 0 AND Height > 0
            AND X + Width  <= 1.0001
            AND Y + Height <= 1.0001
        )
    );
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_TypePlace_DocumentType')
BEGIN
    CREATE INDEX IX_TypePlace_DocumentType ON dbo.DocumentTypePlacements (DocumentTypeId);
END
GO
