import { useEffect, useState, type FormEvent } from 'react'
import { Link, useNavigate, useParams } from 'react-router-dom'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { createEmployeeSchema } from '@asps-dms/shared'
import { Alert } from '../../components/ui/Alert.js'
import { Button } from '../../components/ui/Button.js'
import { TextField } from '../../components/ui/TextField.js'
import { ApiError } from '../../lib/apiError.js'
import { createEmployee, employeeKeys, fetchEmployee, updateEmployee } from './api.js'
import { RequiredDocuments } from './RequiredDocuments.js'

type Field = 'employeeName' | 'joiningDate' | 'department' | 'designation'

const EMPTY = { employeeName: '', joiningDate: '', department: '', designation: '' }

/**
 * Add or edit an employee.
 *
 * One component for both, because the form is the same form: the only
 * differences are where it gets its initial values and which request it sends.
 *
 * The employee code is absent by design. It is generated by the database when
 * the record is created and is immutable afterwards (Sections 11 and 13), so
 * there is nothing here for anyone to type or change.
 */
export function EmployeeFormPage() {
  const params = useParams<{ employeeId?: string }>()
  const employeeId = params.employeeId ? Number(params.employeeId) : null
  const isEdit = employeeId !== null

  const navigate = useNavigate()
  const queryClient = useQueryClient()

  const [values, setValues] = useState(EMPTY)
  const [fieldErrors, setFieldErrors] = useState<Partial<Record<Field, string>>>({})
  const [failure, setFailure] = useState<ApiError | null>(null)

  const existing = useQuery({
    queryKey: employeeKeys.detail(employeeId ?? 0),
    queryFn: () => fetchEmployee(employeeId ?? 0),
    enabled: isEdit,
  })

  useEffect(() => {
    if (!existing.data) return
    setValues({
      employeeName: existing.data.employeeName,
      joiningDate: existing.data.joiningDate,
      department: existing.data.department ?? '',
      designation: existing.data.designation ?? '',
    })
  }, [existing.data])

  const save = useMutation({
    mutationFn: async (input: ReturnType<typeof createEmployeeSchema.parse>) =>
      isEdit ? updateEmployee(employeeId, input) : createEmployee(input),
    onSuccess: async (employee) => {
      // The list counts and the detail both change on a save, so the whole
      // 'employees' prefix goes rather than only the row that was edited.
      await queryClient.invalidateQueries({ queryKey: employeeKeys.all })
      void navigate(`/employees/${employee.employeeId}`, { replace: true })
    },
    onError: (error) => {
      const apiError = error instanceof ApiError ? error : null
      setFailure(apiError)
      setFieldErrors({
        employeeName: apiError?.issueFor('employeeName'),
        joiningDate: apiError?.issueFor('joiningDate'),
        department: apiError?.issueFor('department'),
        designation: apiError?.issueFor('designation'),
      })
    },
  })

  const set = (field: Field) => (event: { target: { value: string } }) => {
    setValues((current) => ({ ...current, [field]: event.target.value }))
  }

  const handleSubmit = (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault()
    setFailure(null)

    // The same schema the API validates with, so the round trip is saved when
    // the input is obviously wrong and the answer is identical when it is not.
    const parsed = createEmployeeSchema.safeParse(values)
    if (!parsed.success) {
      const issues: Partial<Record<Field, string>> = {}
      for (const issue of parsed.error.issues) {
        const field = issue.path[0]
        if (
          field === 'employeeName' ||
          field === 'joiningDate' ||
          field === 'department' ||
          field === 'designation'
        ) {
          issues[field] ??= issue.message
        }
      }
      setFieldErrors(issues)
      return
    }

    setFieldErrors({})
    save.mutate(parsed.data)
  }

  if (isEdit && existing.isLoading) {
    return (
      <main className="p-2 text-sm text-slate-500" role="status">
        Loading employee...
      </main>
    )
  }

  if (isEdit && existing.error) {
    const error = existing.error instanceof ApiError ? existing.error : null
    return (
      <main>
        <Alert title="Could not load that employee" referenceId={error?.referenceId}>
          {error?.message ?? 'Something went wrong.'}
        </Alert>
      </main>
    )
  }

  return (
    <main className={isEdit ? 'mx-auto w-full max-w-2xl' : 'mx-auto w-full max-w-5xl'}>
      <h1 className="text-xl font-semibold text-slate-900">
        {isEdit ? `Edit ${existing.data?.employeeName ?? 'employee'}` : 'Add employee'}
      </h1>
      {isEdit ? (
        <p className="mt-1 font-mono text-xs text-slate-500">{existing.data?.employeeCode}</p>
      ) : (
        <p className="mt-1 text-sm text-slate-600">
          The employee code is generated automatically, and the document checklist is created with
          the record.
        </p>
      )}

      <div className={isEdit ? 'mt-4' : 'mt-4 grid gap-6 lg:grid-cols-2 lg:items-start'}>
      <form
        onSubmit={handleSubmit}
        noValidate
        className="flex flex-col gap-4 rounded-card border border-slate-200 bg-white p-6 shadow-sm"
      >
        {failure ? (
          <Alert title="Could not save" referenceId={failure.referenceId}>
            {failure.message}
          </Alert>
        ) : null}

        <TextField
          label="Employee name"
          autoComplete="off"
          value={values.employeeName}
          error={fieldErrors.employeeName}
          onChange={set('employeeName')}
        />

        <TextField
          label="Joining date"
          type="date"
          value={values.joiningDate}
          error={fieldErrors.joiningDate}
          hint={
            isEdit
              ? 'Changing this does not move deadlines that have already been set.'
              : 'Document deadlines are calculated from this date.'
          }
          onChange={set('joiningDate')}
        />

        <TextField
          label="Department"
          hint="Optional"
          autoComplete="off"
          value={values.department}
          error={fieldErrors.department}
          onChange={set('department')}
        />

        <TextField
          label="Designation"
          hint="Optional"
          autoComplete="off"
          value={values.designation}
          error={fieldErrors.designation}
          onChange={set('designation')}
        />

        <div className="flex items-center gap-3">
          <Button type="submit" busy={save.isPending} busyLabel="Saving...">
            {isEdit ? 'Save changes' : 'Create employee'}
          </Button>
          <Link
            to={isEdit ? `/employees/${employeeId}` : '/employees'}
            className="text-sm text-slate-600 hover:text-slate-900"
          >
            Cancel
          </Link>
        </div>
      </form>

      {/* Only when adding. On edit the checklist already exists, and the
          employee's own page shows it with what has actually come in. */}
      {isEdit ? null : <RequiredDocuments joiningDate={values.joiningDate} />}
      </div>
    </main>
  )
}
