import { useEffect, useState, type FormEvent } from 'react'
import { Link, useNavigate, useParams } from 'react-router-dom'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { GENDERS, computeDueDate, createEmployeeSchema, type Employee } from '@asps-dms/shared'
import { Alert } from '../../components/ui/Alert.js'
import { Button } from '../../components/ui/Button.js'
import { DateField } from '../../components/ui/DateField.js'
import { Select } from '../../components/ui/Select.js'
import { TextField } from '../../components/ui/TextField.js'
import { ApiError } from '../../lib/apiError.js'
import { parseDisplayDate } from '../../lib/format.js'
import { createEmployee, employeeKeys, fetchEmployee, updateEmployee } from './api.js'
import {
  RequiredDocuments,
  missingMandatory,
  type DueDateOverrides,
  type SelectedFiles,
} from './RequiredDocuments.js'
import { DocumentChecklist } from '../documents/DocumentChecklist.js'
import { updateDocumentDeadline, uploadDocument } from '../documents/api.js'
import {
  fetchEmployeeDocuments,
  fetchReference,
  listDocumentTypes,
  documentTypeKeys,
  referenceKeys,
} from './api.js'

type Field = 'gender' | 'employeeCode' | 'employeeName' | 'joiningDate' | 'department' | 'designation'

const GENDER_CHOICES = GENDERS.map((value) => ({ value, label: value }))

/**
 * The list, plus whatever the record already says.
 *
 * An employee edited after their department was deactivated - or imported with
 * a spelling not in the list - must not have it silently changed to blank by
 * opening the form. The current value is offered alongside the list.
 */
function optionsFor(
  names: readonly string[] | undefined,
  current: string,
): { value: string; label: string }[] {
  const list = names ?? []
  const all = current && !list.includes(current) ? [current, ...list] : list
  return all.map((name) => ({ value: name, label: name }))
}

const EMPTY = { gender: '', employeeCode: '', employeeName: '', joiningDate: '', department: '', designation: '' }

/**
 * Add or edit an employee.
 *
 * One component for both, because the form is the same form: the only
 * differences are where it gets its initial values and which request it sends.
 *
 * The employee code is absent by design. It is generated by the database when
 * the record is created and is immutable afterwards (Sections 11 and 13), so
 * there is nothing here for anyone to type or change.
 */
export function EmployeeFormPage() {
  const params = useParams<{ employeeId?: string }>()
  const employeeId = params.employeeId ? Number(params.employeeId) : null
  const isEdit = employeeId !== null

  const navigate = useNavigate()
  const queryClient = useQueryClient()

  const [values, setValues] = useState(EMPTY)
  const [fieldErrors, setFieldErrors] = useState<Partial<Record<Field, string>>>({})
  const [failure, setFailure] = useState<ApiError | null>(null)
  const [overrides, setOverrides] = useState<DueDateOverrides>({})
  // What is typed in each due-date box, kept as typed so a half-finished
  // '01/0' is not rewritten under the person's fingers.
  const [dueText, setDueText] = useState<Record<number, string>>({})
  // The mandatory documents, held until there is a record to attach them to.
  const [files, setFiles] = useState<SelectedFiles>({})
  const [triedToSave, setTriedToSave] = useState(false)
  // Set once the record exists. Until then there are no document rows to
  // upload into, which is why this is two steps rather than one form.
  const [created, setCreated] = useState<Employee | null>(null)

  const reference = useQuery({
    queryKey: referenceKeys.all,
    queryFn: fetchReference,
    staleTime: 30 * 60 * 1000,
  })

  const typesQuery = useQuery({
    queryKey: documentTypeKeys.all,
    queryFn: listDocumentTypes,
    staleTime: 5 * 60 * 1000,
    enabled: !isEdit,
  })

  const existing = useQuery({
    queryKey: employeeKeys.detail(employeeId ?? 0),
    queryFn: () => fetchEmployee(employeeId ?? 0),
    enabled: isEdit,
  })

  useEffect(() => {
    if (!existing.data) return
    setValues({
      gender: existing.data.gender ?? '',
      employeeCode: existing.data.employeeCode,
      employeeName: existing.data.employeeName,
      joiningDate: existing.data.joiningDate,
      department: existing.data.department ?? '',
      designation: existing.data.designation ?? '',
    })
  }, [existing.data])

  /**
   * Applies any deadline the person changed on the form.
   *
   * Only the rows they actually changed: a date left at its default is already
   * exactly what the server computed, and PATCHing it would write a deliberate
   * override into the audit trail for a decision nobody made.
   *
   * A failure here does not fail the creation. The employee exists and the
   * dates are the standard ones, which is recoverable from the checklist;
   * throwing away a saved record over a deadline would not be.
   */
  const applyDueDateOverrides = async (employee: Employee) => {
    const changed = Object.entries(overrides).filter(([typeId, dueDate]) => {
      if (!/^\d{4}-\d{2}-\d{2}$/.test(dueDate)) return false
      const type = typesQuery.data?.find((t) => t.documentTypeId === Number(typeId))
      if (!type) return false
      const standard = computeDueDate(employee.joiningDate, type.deadlineValue, type.deadlineUnit)
      return dueDate !== standard
    })
    if (changed.length === 0) return

    try {
      const documents = await fetchEmployeeDocuments(employee.employeeId)
      await Promise.all(
        changed.map(([typeId, dueDate]) => {
          const document = documents.find((d) => d.documentTypeId === Number(typeId))
          if (!document) return Promise.resolve()
          return updateDocumentDeadline(document.documentId, dueDate, 'Set when the employee was added')
        }),
      )
    } catch {
      // Left deliberately quiet, for the reason above. The checklist shows the
      // dates that were actually stored.
    }
  }

  /**
   * Sends the documents that were attached on the form.
   *
   * They could not be uploaded before now: the checklist rows are created with
   * the employee, so there was nothing to attach them to. A failure is not
   * silent here - unlike a deadline, a missing identity document is the thing
   * that was insisted on - so it is reported on the next step, where the row
   * shows as still pending and can be uploaded again.
   */
  const uploadHeldFiles = async (employee: Employee) => {
    const chosen = Object.entries(files)
    if (chosen.length === 0) return

    const documents = await fetchEmployeeDocuments(employee.employeeId)
    for (const [typeId, file] of chosen) {
      const document = documents.find((d) => d.documentTypeId === Number(typeId))
      if (!document) continue
      try {
        await uploadDocument(document.documentId, file)
      } catch {
        // Left for the checklist to show. Throwing here would lose the employee
        // record that was just created successfully.
      }
    }
  }

  const save = useMutation({
    mutationFn: async (input: ReturnType<typeof createEmployeeSchema.parse>) =>
      isEdit ? updateEmployee(employeeId, input) : createEmployee(input),
    onSuccess: async (employee) => {
      if (!isEdit) {
        await applyDueDateOverrides(employee)
        await uploadHeldFiles(employee)
      }
      // The list counts and the detail both change on a save, so the whole
      // 'employees' prefix goes rather than only the row that was edited.
      await queryClient.invalidateQueries({ queryKey: employeeKeys.all })

      if (isEdit) {
        void navigate(`/employees/${employee.employeeId}`, { replace: true })
        return
      }
      // Stay here. The documents can only be uploaded now that the checklist
      // rows exist, and sending someone to another screen to do the obvious
      // next thing is how half-filled records happen.
      setCreated(employee)
    },
    onError: (error) => {
      const apiError = error instanceof ApiError ? error : null
      setFailure(apiError)
      setFieldErrors({
        employeeCode: apiError?.issueFor('employeeCode'),
        employeeName: apiError?.issueFor('employeeName'),
        joiningDate: apiError?.issueFor('joiningDate'),
        department: apiError?.issueFor('department'),
        designation: apiError?.issueFor('designation'),
      })
    },
  })

  const set = (field: Field) => (event: { target: { value: string } }) => {
    setValues((current) => ({ ...current, [field]: event.target.value }))
  }

  const handleSubmit = (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault()
    setFailure(null)

    // The same schema the API validates with, so the round trip is saved when
    // the input is obviously wrong and the answer is identical when it is not.
    const parsed = createEmployeeSchema.safeParse(values)
    if (!parsed.success) {
      const issues: Partial<Record<Field, string>> = {}
      for (const issue of parsed.error.issues) {
        const field = issue.path[0]
        if (
          field === 'employeeName' ||
          field === 'joiningDate' ||
          field === 'department' ||
          field === 'designation'
        ) {
          issues[field] ??= issue.message
        }
      }
      setFieldErrors(issues)
      return
    }

    setFieldErrors({})

    // The two identity documents are the point of the record: an employee whose
    // Aadhaar and PAN were "coming later" is exactly what this stops.
    if (!isEdit && missingMandatory(typesQuery.data, files).length > 0) {
      setTriedToSave(true)
      return
    }

    save.mutate(parsed.data)
  }

  if (isEdit && existing.isLoading) {
    return (
      <main className="p-2 text-sm text-slate-500" role="status">
        Loading employee...
      </main>
    )
  }

  if (isEdit && existing.error) {
    const error = existing.error instanceof ApiError ? existing.error : null
    return (
      <main>
        <Alert title="Could not load that employee" referenceId={error?.referenceId}>
          {error?.message ?? 'Something went wrong.'}
        </Alert>
      </main>
    )
  }

  if (created) {
    return <UploadStep employee={created} />
  }

  return (
    <main className={isEdit ? 'mx-auto w-full max-w-2xl' : 'mx-auto w-full max-w-6xl'}>
      <Link
        to={isEdit ? `/employees/${employeeId}` : '/employees'}
        className="text-sm text-slate-600 hover:text-slate-900"
      >
        &larr; {isEdit ? 'Back to the employee' : 'Employees'}
      </Link>

      <header className="mt-2">
        <h1 className="text-xl font-semibold text-slate-900">
          {isEdit ? `Edit ${existing.data?.employeeName ?? 'employee'}` : 'Add employee'}
        </h1>
        {isEdit ? (
          <p className="mt-1 font-mono text-xs text-slate-500">{existing.data?.employeeCode}</p>
        ) : (
          <p className="mt-1 text-sm text-slate-600">
            The checklist is created with the record. The two identity documents are attached now;
            the rest have deadlines and follow later.
          </p>
        )}
      </header>

      <div className={isEdit ? 'mt-6' : 'mt-6 grid items-start gap-6 lg:grid-cols-[minmax(0,22rem)_minmax(0,1fr)]'}>
      <form
        onSubmit={handleSubmit}
        noValidate
        className="flex flex-col gap-4 rounded-card border border-slate-200 bg-white p-6 shadow-sm"
      >
        {failure ? (
          <Alert title="Could not save" referenceId={failure.referenceId}>
            {failure.message}
          </Alert>
        ) : null}

        <h2 className="text-sm font-semibold text-slate-900">Employee details</h2>

        {isEdit ? null : (
          <TextField
            label="Employee ID"
            hint="The company's own number, as printed on the service card. It cannot be changed later."
            autoComplete="off"
            value={values.employeeCode}
            error={fieldErrors.employeeCode}
            onChange={set('employeeCode')}
          />
        )}

        <TextField
          label="Employee name"
          autoComplete="off"
          value={values.employeeName}
          error={fieldErrors.employeeName}
          onChange={set('employeeName')}
        />

        <DateField
          label="Joining date"
          value={values.joiningDate}
          error={fieldErrors.joiningDate}
          hint={
            isEdit
              ? 'Changing this does not move deadlines that have already been set.'
              : 'Document deadlines are calculated from this date.'
          }
          onChange={set('joiningDate')}
        />

        <Select
          label="Department"
          placeholder="Not set"
          value={values.department}
          options={optionsFor(reference.data?.departments, values.department)}
          error={fieldErrors.department}
          onChange={set('department')}
        />

        <Select
          label="Designation"
          placeholder="Not set"
          value={values.designation}
          options={optionsFor(reference.data?.designations, values.designation)}
          error={fieldErrors.designation}
          onChange={set('designation')}
        />

        <Select
          label="Gender"
          value={values.gender}
          options={GENDER_CHOICES}
          placeholder="Not recorded"
          onChange={set('gender')}
        />

        {!isEdit && triedToSave && missingMandatory(typesQuery.data, files).length > 0 ? (
          <p className="rounded-md bg-red-50 px-3 py-2 text-sm text-status-rejected">
            Attach {missingMandatory(typesQuery.data, files)
              .map((type) => type.documentName)
              .join(' and ')}{' '}
            before creating this employee.
          </p>
        ) : null}

        <div className="mt-2 flex items-center gap-3 border-t border-slate-100 pt-4">
          <Button type="submit" busy={save.isPending} busyLabel="Saving...">
            {isEdit ? 'Save changes' : 'Create employee'}
          </Button>
          <Link
            to={isEdit ? `/employees/${employeeId}` : '/employees'}
            className="text-sm text-slate-600 hover:text-slate-900"
          >
            Cancel
          </Link>
        </div>
      </form>

      {/* Only when adding. On edit the checklist already exists, and the
          employee's own page shows it with what has actually come in. */}
      {isEdit ? null : (
        <RequiredDocuments
          joiningDate={values.joiningDate}
          dueText={dueText}
          onDueDateText={(documentTypeId, text) => {
            setDueText((current) => ({ ...current, [documentTypeId]: text }))
            const iso = parseDisplayDate(text)
            if (iso) setOverrides((current) => ({ ...current, [documentTypeId]: iso }))
          }}
          files={files}
          showMissing={triedToSave}
          onFile={(documentTypeId, file) =>
            setFiles((current) => {
              const next = { ...current }
              if (file) next[documentTypeId] = file
              else delete next[documentTypeId]
              return next
            })
          }
        />
      )}
      </div>
    </main>
  )
}

/**
 * Step two: the record exists, so the documents can go in.
 *
 * The same checklist the employee's own page uses, rather than a second upload
 * screen that would drift from it: one row per document, a tick once a file is
 * in, and Pending with its date until then.
 */
function UploadStep({ employee }: { employee: Employee }) {
  const documents = useQuery({
    queryKey: employeeKeys.documents(employee.employeeId),
    queryFn: () => fetchEmployeeDocuments(employee.employeeId),
  })

  const done = (documents.data ?? []).filter((d) => d.originalFileName !== null).length
  const total = documents.data?.length ?? 0

  return (
    <main>
      <div className="rounded-card border border-status-verified/30 bg-green-50 p-4">
        <h1 className="text-base font-semibold text-slate-900">
          {employee.employeeName} added as {employee.employeeCode}
        </h1>
        <p className="mt-1 text-sm text-slate-700">
          Upload whatever you have now - the rest stays Pending and is chased by the reminder.
          {total > 0 ? ` ${done} of ${total} in.` : ''}
        </p>
        <div className="mt-3 flex items-center gap-3">
          <Link
            to={`/employees/${employee.employeeId}`}
            className="text-sm font-medium text-brand-700 hover:text-brand-800"
          >
            Open the employee record
          </Link>
          <Link to="/employees/new" className="text-sm text-slate-600 hover:text-slate-900">
            Add another employee
          </Link>
        </div>
      </div>

      <h2 className="mt-6 text-sm font-semibold text-slate-900">Document checklist</h2>
      <div className="mt-2">
        <DocumentChecklist documents={documents.data} isLoading={documents.isLoading} />
      </div>
    </main>
  )
}
